version: '3'

services:
  database:
    container_name: Mysql-database
    image: mysql:latest
    ports:
      - 3306:3306
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: Testdb
      MYSQL_USER: deniz
      MYSQL_PASSWORD: turkmen

    volumes:
      - /mnt/data/mysql:/var/lib/mysql
